 FAIL  src/updateTask/UpdateTask.repo.spec.ts (6.979 s)
  ● Console

    console.log
      [ { status: 'completed', task_unid: '1' } ]

      at UpdateTaskRepo.updatetask (updateTask/UpdateTask.repo.ts:14:13)

    console.log
      []

      at UpdateTaskRepo.updatetask (updateTask/UpdateTask.repo.ts:14:13)

  ● UpdateTaskRepo › updatetask › should throw an error if the database call fails
                                                                                                                                     
    expect(received).rejects.toThrow()                                                                                               
                                                                                                                                     
    Received promise resolved instead of rejected                                                                                    
    Resolved to value: undefined                                                                                                     
                                                                                                                                     
      52 |       oraUtil.executeQuery = jest.fn().mockRejectedValue(new Error('DB Error'));                                          
      53 |
    > 54 |       await expect(repo.updatetask(req)).rejects.toThrow('DB Error');
         |             ^
      55 |     });
      56 |   });
      57 | });

      at expect (../node_modules/expect/build/index.js:113:15)
      at Object.<anonymous> (updateTask/UpdateTask.repo.spec.ts:54:13)

 PASS  src/updateTask/UpdateTask.controller.spec.ts (7.258 s)
  ● Console
                     
